### ISSUE TITLE
Update the Boilerplate to SDK 8.2.1

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/aepp-boilerplate#20]
The boilerplate needs some love:

- [ ] Update the SDK to 8.2.1
- [ ] Make sure that the boilerplate still connects & works with
  - [ ] Base Aepp
  - [ ] Superhero Wallet
- [ ] Update all other dependencies to the newest version
- [ ] Switch CI to Github Actions

**Comment by marc0olo** [comment]
should we also get rid of https://github.com/aeternity/aepp-components as this is archived?
=> aepp-components will probably be "unarchived" and can stay in the boilerplate

I would also add another task:
- switching from travis to github actions to run the tests

**Comment by marc0olo** [comment]
@kenodressel I opened an issue in the aeternity repo now for that. we can close it here IMO, see https://github.com/aeternity/aepp-boilerplate-vue/issues/1

cc @ErkanKanden, @omar-saadoun
